version: '3.0'
services:

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    networks: 
      - proxy_network
    ports: 
      - 27017:27017
    volumes: 
      - ./mongo-volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 2020aiot
      
  mongo-express:
    image: mongo-express
    container_name: mongodb-express
    restart: always
    networks: 
      - proxy_network
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 2020aiot
  
  proxy-scylla:
    image: wildcat/scylla:1.1.7
    container_name: proxy-scylla
    networks: 
      - proxy_network
    restart: always
    ports:
      - 8899:8899
      - 8081:8081
    volumes: 
      - ./scylla:/var/www/scylla
networks: 
  proxy_network:
    driver: bridge   
